version: "3"
services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=golf
    depends_on:
      - prometheus    
  # node-app:
  #   build: .
  #   container_name: "golf-node"
  #   depends_on:
  #     - prometheus
  #     - grafana
  #   command: ["npm", "start"]
  #   ports:
  #     - "8080:8080"